(TeX-add-style-hook
 "main"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("article" "11pt")))
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("geometry" "dvips" "letterpaper" "margin=1in") ("cleveref" "noabbrev" "capitalize")))
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (TeX-run-style-hooks
    "latex2e"
    "article"
    "art11"
    "amscd"
    "amsmath"
    "amstext"
    "bbold"
    "bm"
    "booktabs"
    "color"
    "easybmat"
    "etex"
    "framed"
    "geometry"
    "graphicx"
    "hyperref"
    "cleveref"
    "mathtools"
    "setspace"
    "verbatim")
   (TeX-add-symbols
    '("charfusion" ["argument"] 2)
    '("bmrob" 1)
    '("code" 1)
    '("precode" 1)
    '("TAB" 1)
    '("tab" 1)
    '("lgndr" 2)
    '("FIG" 1)
    '("fig" 1)
    "Mobius"
    "Holder"
    "Rouche"
    "Ito"
    "Kondo"
    "Levy"
    "Cramer"
    "Godel"
    "Carath"
    "Caratheodory"
    "Hopital"
    "lvec"
    "ra"
    "la"
    "cupdot"
    "bigcupdot"
    "RR"
    "QQ"
    "NN"
    "TT"
    "ZZ"
    "DD"
    "HH"
    "CC"
    "PP"
    "EE"
    "FF"
    "Fp"
    "TrivGp"
    "One"
    "RP"
    "CP"
    "nn"
    "vv"
    "ww"
    "xx"
    "yy"
    "one"
    "fp"
    "fq"
    "fg"
    "fh"
    "fa"
    "fb"
    "fc"
    "fm"
    "so"
    "gl"
    "sA"
    "sB"
    "sC"
    "sD"
    "sE"
    "sF"
    "sG"
    "sH"
    "sI"
    "sL"
    "sM"
    "sN"
    "sO"
    "sP"
    "sR"
    "sS"
    "sT"
    "sU"
    "sV"
    "sX"
    "sY"
    "ThmBr"
    "br"
    "BR"
    "picspace"
    "hs"
    "HS"
    "hr"
    "hrs"
    "Var"
    "Cov"
    "disc"
    "Ann"
    "Ass"
    "Soc"
    "Supp"
    "Spec"
    "maxSpec"
    "N"
    "Tr"
    "Hom"
    "Der"
    "End"
    "Ind"
    "Aut"
    "Gal"
    "Sym"
    "Rad"
    "Id"
    "Ad"
    "ad"
    "Pow"
    "diam"
    "img"
    "sgn"
    "ch"
    "Res"
    "ord"
    "cont"
    "ab"
    "Orb"
    "Syl"
    "Irr"
    "Frac"
    "sep"
    "per"
    "GL"
    "PGL"
    "PSL"
    "SL"
    "oO"
    "SO"
    "PSO"
    "Sp"
    "PSp"
    "U"
    "SU"
    "PSU"
    "iso"
    "eqdf"
    "eqd"
    "eqqu"
    "xto"
    "dto"
    "into"
    "xinto"
    "onto"
    "xonto"
    "isoto"
    "upto"
    "downto"
    "Implies"
    "ImpliedBy"
    "Iff"
    "Pfright"
    "Pfleft"
    "sm"
    "sectionline"
    "HC"
    "CHC"
    "SK"
    "SDP"
    "SOS"
    "PE"
    "PS"
    "tEE"
    "tCov"
    "sfP"
    "argmin"
    "argmax"
    "diag"
    "vrad"
    "rk"
    "rkeff"
    "GOE"
    "ssG"
    "bA"
    "bB"
    "bD"
    "bG"
    "bH"
    "bP"
    "bQ"
    "bR"
    "bW"
    "bX"
    "ba"
    "bb"
    "bg"
    "bv"
    "bw"
    "bx"
    "moverlay")
   (LaTeX-add-labels
    "thm:single-obs-recovery")
   (LaTeX-add-environments
    '("proof" LaTeX-env-args ["argument"] 0)
    "theorem"
    "lemma"
    "question"
    "definition"
    "example"
    "proposition"
    "corollary"
    "conjecture")
   (LaTeX-add-bibliographies)))

